version: '3.8'

services:
  # Banco de dados MongoDB
  mongodb:
    image: mongo:7.0
    container_name: financas_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: financas_app
    networks:
      - financas_network

  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: financas_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=financas_app
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - financas_network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financas_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - financas_network

volumes:
  mongodb_data:
    driver: local

networks:
  financas_network:
    driver: bridge